### PR TITLE
updated v0.11.6

### PR DESCRIPTION
**Pull request by arnabanimesh**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by arnabanimesh** [comment]
@conda-forge-admin, please rerender

**Comment by 0xbe7a** [comment]
```
    = note: x86_64-apple-darwin13.4: error: unable to execute command: Segmentation fault: 11
            x86_64-apple-darwin13.4: error: linker command failed due to signal (use -v to see invocation)
```

Looks like https://github.com/conda-forge/polars-feedstock/issues/259

**Comment by arnabanimesh** [comment]
@conda-forge-admin, please rerender

**Comment by arnabanimesh** [comment]
@conda-forge-admin, please rerender

**Comment by arnabanimesh** [comment]
@conda-forge-admin, please rerender

**Comment by arnabanimesh** [comment]
@conda-forge-admin, please rerender

**Pull request closed without merging**
